version: "3.8"

services:
  db_server_service:
    image: postgres:14.8
    container_name: db_server_container
    ports:
      - "${DB_SERVER_PORT}:5432"
    env_file:
      - ./db_server/.env
    volumes:
      - ./db_server/data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  api_server_service:
    image: fastapi_server
    container_name: api_server_container
    ports:
      - "${API_SERVER_PORT}:8000"
    env_file:
      - ./api_server/.env
    volumes:
      - ./api_server:/work
    depends_on:
      db_server_service:
        condition: service_healthy
    command: ["uvicorn", "server:app", "--host", "0.0.0.0", "--port", "8000"]
